services:
  llama:
    image: ollama/ollama:0.11.3
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  php:
    build:
      context: ../backend
      dockerfile: ../deployment/php/php.dockerfile

    volumes:
      - ../backend:/var/www/html

  composer:
    build:
      context: ./composer
      dockerfile: composer.dockerfile

    volumes:
      - ../backend:/var/www/html
    working_dir: /var/www/html

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../backend/public:/var/www/html/public # Подключаем публичную папку Laravel
    depends_on:
      - php
  mysql:
    image: mysql:latest

    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
      retries: 3
      timeout: 5s

    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build:
      context: ../
      dockerfile: deployment/frontend/frontend.dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      # - /app/node_modules # node_modules не затирается volume-ом
    working_dir: /app
    command: npm run dev -- --host

volumes:
  ollama_data:
  mysql_data:
