services:
  llama:
    image: ollama/ollama:0.11.3
    container_name: ollama-llama
    ports:
      - "11434:11434"
    environment:
      # Полный контекст модели (максимум, на котором она обучена)
      - OLLAMA_CTX_PER_SEQ=32768
      # Квантование для CPU, уменьшает потребление RAM и ускоряет генерацию
      - OLLAMA_QUANTIZATION=Q4_K_M
      # Включаем потоковую генерацию (streaming), чтобы ответы приходили сразу по частям
      - OLLAMA_STREAM=1
      # Таймауты можно регулировать при необходимости
      - OLLAMA_TIMEOUT=120
    deploy:
      resources:
        limits:
          memory: 32g # максимум RAM для контейнера
        reservations:
          memory: 16g # минимальный резерв RAM
    volumes:
      - ollama_data:/root/.ollama

  php:
    build:
      context: ../backend
      dockerfile: ../deployment/php/php.dockerfile

    volumes:
      - ../backend:/var/www/html

  composer:
    build:
      context: ./composer
      dockerfile: composer.dockerfile

    volumes:
      - ../backend:/var/www/html
    working_dir: /var/www/html

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../backend/public:/var/www/html/public # Подключаем публичную папку Laravel
    depends_on:
      - php
  mysql:
    image: mysql:latest

    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
      retries: 3
      timeout: 5s

    volumes:
      - mysql_data:/var/lib/mysql

  admin-one-vue-tailwind:
    build:
      context: ../
      dockerfile: deployment/frontend/frontend.dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../admin-one-vue-tailwind:/app
    working_dir: /app
    command: npm run dev -- --host

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  queue-worker:
    build:
      context: ../backend
      dockerfile: ../deployment/php/php.dockerfile
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../backend:/var/www/html

    command: >
      php artisan queue:work redis
       --queue=ai
       --sleep=1
       --tries=3
       --timeout=90
       --verbose

    restart: unless-stopped

volumes:
  ollama_data:
  mysql_data:
  redis_data:
